// angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { AverageMethod, ConfusionMatrix } from '@fullexpression/confusion-matrix-stats'

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss']
})
export class AppComponent {
    title = 'ConfusionMatrixAngularExamples';

    confusionMatrix = new ConfusionMatrix({
        labels: ["Happiness", "Sadness", "Disgust"],
        matrix: [[50, 2, 3],
        [8, 50, 5],
        [2, 5, 50]]
    });

    get accuracy(): number {
        return this.confusionMatrix.accuracy();
    }

    get f1Score(): number {
        return this.confusionMatrix.f1Score({ label: "Sadness", average: AverageMethod.Macro });
    }

}

<div class="wrapper">
    <div class="line accuracy">
        <label class="description">Accuracy value for the all matrix:</label>
        <label class="value">{{accuracy}}</label>
    </div>

    <div class="line f1Score">
        <label class="description">F1Score, only for "sadness" class, using the Macro average method:</label>
        <label class="value">{{f1Score}}</label>
    </div>
</div>

// react/src/App.js
import './App.css';
import { ConfusionMatrix, AverageMethod } from '@fullexpression/confusion-matrix-stats';

const confusionMatrix = new ConfusionMatrix({
    labels: ["Happiness", "Sadness", "Disgust"], 
    matrix: [[50, 2, 3],
             [8, 50 ,5],
             [2, 5 ,50]]
});


function App() {
  const accuracy = confusionMatrix.accuracy();
  const f1Score = confusionMatrix.f1Score({ label: "Sadness", average: AverageMethod.Macro })
  return (
    <div className="App">
      <header className="App-header">
        <label class="description">Accuracy value for the all matrix:</label>
        <label class="value">{accuracy}</label>
        <br></br>
        <label class="description">F1Score, only for "sadness" class, using the Macro average method:</label>
        <label class="value">{f1Score}</label>
      </header>
    </div>
  );
}

export default App;
